version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "8000:5432/tcp"
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: registration
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
